### ISSUE TITLE
Sloppy map erase

### ISSUE THREAD

**Issue by coderdj** [coderdj/redax#14]
In the strax output the file handles are stored in a map. A second map stores a mutex for each file handle so that only one thread writes to it at once. Once a file is sufficiently old it is renamed and closed so strax can start on it and its entry is removed from the map.

Except that's dumb. You can't erase elements from the map while other threads are still using it to access file handles or you get seg faults (as we do). 

In commit 779c955111fa5cd925d9cc0395c3444b47952f45 I just stopped clearing the map, which is hopefully fine for now but isn't a good long term solution since open file handles start piling up. What we really need is a smarter way to handle the clearing, which probably involves more concurrency control. 

Fun side note: there is a locking device called a semaphore that seems like just what I need for this but C++ apparently does not contain them.

**Comment by coderdj** [comment]
Actually I think that's all rubbish. We're accessing the map only by key, not iterating, except in the CleanUp function... so the only explanation I have is that CleanUp is getting called by multiple threads at once.

**Comment by coderdj** [comment]
Closing file 000035
20 files remain
Closing file 000019
23 files remain
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Thread 7 "main" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff0d63700 (LWP 2107)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff69c2801 in __GI_abort () at abort.c:79
#2  0x00007ffff72368b7 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff723ca06 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff723ca41 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff723cc74 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff723d1ec in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x000055555556a1d9 in StraxFileHandler::CleanUp (this=this@entry=0x5555557df800, 
    back_from_id=back_from_id@entry=35, force_all=force_all@entry=false) at StraxFileHandler.cc:149
#8  0x000055555556de37 in StraxFileHandler::InsertFragments (this=<optimized out>, 
    parsed_fragments=std::map with 5 elements = {...}) at StraxFileHandler.cc:89
#9  0x0000555555572692 in StraxInserter::ReadAndInsertData (this=this@entry=0x7fffec0013c0)
    at StraxInserter.cc:294
#10 0x000055555555c393 in DAQController::ProcessingThreadWrapper (data=0x7fffec0013c0)
    at DAQController.cc:299
#11 0x0000555555560cc6 in std::__invoke_impl<void*, void* (*)(void*), void*> (__f=<optimized out>)
    at /usr/include/c++/7/bits/invoke.h:60
#12 std::__invoke<void* (*)(void*), void*> (__fn=<optimized out>) at /usr/include/c++/7/bits/invoke.h:96
#13 std::thread::_Invoker<std::tuple<void* (*)(void*), void*> >::_M_invoke<0ul, 1ul> (
    this=<optimized out>) at /usr/include/c++/7/thread:234
#14 std::thread::_Invoker<std::tuple<void* (*)(void*), void*> >::operator() (this=<optimized out>)
    at /usr/include/c++/7/thread:243
#15 std::thread::_State_impl<std::thread::_Invoker<std::tuple<void* (*)(void*), void*> > >::_M_run (
    this=<optimized out>) at /usr/include/c++/7/thread:186
#16 0x00007ffff726757f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#17 0x00007ffff6d7a6db in start_thread (arg=0x7ffff0d63700) at pthread_create.c:463
#18 0x00007ffff6aa388f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb)

**Comment by coderdj** [comment]
This was completely refactored
