### ISSUE TITLE
File does not exist in strax writer

### ISSUE THREAD

**Issue by coderdj** [coderdj/redax#16]
```
terminate called after throwing an instance of 'std::experimental::filesystem::v1::__cxx11::filesystem_error'
  what():  filesystem error: cannot create directory: No such file or directory [/data/xenon/raw/xenonnt/001815/000000_temp]

Thread 6 "main" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff135d700 (LWP 1571)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff69c2801 in __GI_abort () at abort.c:79
#2  0x00007ffff72368b7 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff723ca06 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff723ca41 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff723cc74 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x0000555555584037 in std::experimental::filesystem::v1::create_directory(std::experimental::filesystem::v1::__cxx11::path const&) ()
#7  0x000055555556d357 in StraxFileHandler::InsertFragments (this=<optimized out>, parsed_fragments=std::map with 2 elements = {...}) at StraxFileHandler.cc:74
#8  0x0000555555572826 in StraxInserter::ReadAndInsertData (this=this@entry=0x7fffec001200) at StraxInserter.cc:298
#9  0x000055555555c393 in DAQController::ProcessingThreadWrapper (data=0x7fffec001200) at DAQController.cc:299
#10 0x0000555555560cba in std::__invoke_impl<void*, void* (*)(void*), void*> (__f=<optimized out>) at /usr/include/c++/7/bits/invoke.h:60
#11 std::__invoke<void* (*)(void*), void*> (__fn=<optimized out>) at /usr/include/c++/7/bits/invoke.h:96
#12 std::thread::_Invoker<std::tuple<void* (*)(void*), void*> >::_M_invoke<0ul, 1ul> (this=<optimized out>) at /usr/include/c++/7/thread:234
#13 std::thread::_Invoker<std::tuple<void* (*)(void*), void*> >::operator() (this=<optimized out>) at /usr/include/c++/7/thread:243
#14 std::thread::_State_impl<std::thread::_Invoker<std::tuple<void* (*)(void*), void*> > >::_M_run (this=<optimized out>) at /usr/include/c++/7/thread:186
#15 0x00007ffff726757f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#16 0x00007ffff6d7a6db in start_thread (arg=0x7ffff135d700) at pthread_create.c:463
#17 0x00007ffff6aa388f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 
```
I believe it. It probably doesn't exist. This was on reader0, which has a low rate, so could be due to the issue of not creating files if there are no events.

**Comment by coderdj** [comment]
I forgot to mount the nfs partition after rebooting that machine. Dum dum dum dum dum.
